[versions]
agp = "8.11.2"
converterGson = "3.0.0"
koinAndroidVersion = "4.2.1"
koinAndroidxCompose = "4.2.1"
kotlin = "2.3.20"
loggingInterceptor = "5.3.2"
materialIconsExtended = "1.7.8"
retrofit = "3.0.0"
roomCompiler = "2.8.4"
roomKtx = "2.8.4"
roomRuntime = "2.8.4"
tensorflowLite = "2.17.0"
navigationRuntimeAndroid = "2.9.7"
uiTextGoogleFontsVersion = "1.10.6"
navigationComposeAndroid = "2.9.7"
material3Android = "1.4.0"
voskAndroidVersion = "0.3.75"

[libraries]
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
koin-android-v420 = { module = "io.insert-koin:koin-android", version.ref = "koinAndroidVersion" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
androidx-navigation-runtime-android = { group = "androidx.navigation", name = "navigation-runtime-android", version.ref = "navigationRuntimeAndroid" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLite" }
ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFontsVersion" }
androidx-navigation-compose-android = { group = "androidx.navigation", name = "navigation-compose-android", version.ref = "navigationComposeAndroid" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
vosk-android = { module = "com.alphacephei:vosk-android", version.ref = "voskAndroidVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

